(() => {
'use strict';
const KEY='tag-relay-v3', HOST='tag-relay-v3-host', OLD='tag-relay-v2', V=3, $=id=>document.getElementById(id);
let s=null,h=null,pending=null,view='choose',scanner=null,scanBusy=false,shownOffer='',shownHost='',lastChallenge=-1;
const now=()=>Date.now(), stamp=t=>new Date(t).toLocaleString(), ident=()=>Array.from(crypto.getRandomValues(new Uint8Array(12)),b=>b.toString(16).padStart(2,'0')).join('');
const idOK=x=>typeof x==='string'&&/^[a-f0-9]{24}$/.test(x);
const validRules=r=>r&&(/^(?:[1-9]|1\d|20|U)$/.test(String(r.lives)))&&Number.isInteger(r.seconds)&&r.seconds>=30&&r.seconds<=600&&['none','one','two'].includes(r.medic)&&r.wait===(r.medic==='two'?30:0);
const rulesText=r=>`${r.lives==='U'?'Unlimited':r.lives+' lives'} · ${r.seconds}s bleedout · ${r.medic==='none'?'no medic':r.medic==='one'?'one-scan medic':'two-scan medic, 30s apart'}`;
function notice(text){$('notice').textContent=text||''}
function event(x,msg){x.events.push({at:new Date().toISOString(),message:msg})}
function save(next){try{localStorage.setItem(KEY,JSON.stringify(next));s=next;render();return true}catch(e){notice('SAVE FAILED. Stop play and export/recover storage before continuing.');return false}}
function change(fn){if(!s)return false;const next=JSON.parse(JSON.stringify(s));fn(next);return save(next)}
function saveHost(next){try{localStorage.setItem(HOST,JSON.stringify(next));h=next;render();return true}catch(e){notice('Host rules could not be saved. Do not share the QRs.');return false}}
function qr(el,text,size=215){el.replaceChildren();if(typeof QRCode!=='function'){el.textContent='QR library unavailable. Load once online before offline play.';return}try{new QRCode(el,{text,width:size,height:size,correctLevel:QRCode.CorrectLevel.M})}catch(e){el.textContent='QR drawing failed. Check cached library.'}}
function payload(type,...args){return JSON.stringify(['TR3',type,V,...args])}
function joinCode(team){return payload('J',h.gid,h.game,h.rules.lives,h.rules.seconds,h.rules.medic,h.rules.wait,team)}
function baseCode(team){return payload('B',h.gid,team)}
function offerCode(){const o=s.offer,r=s.rules;return payload('O',s.gid,r.lives,r.seconds,r.medic,r.wait,s.team,s.id,s.name,o.n,o.id,o.at,o.deadline,Math.floor(now()/8000))}
function parse(text){let a;try{a=JSON.parse(String(text||'').trim())}catch(e){throw Error('Invalid Tag Relay QR')}if(!Array.isArray(a)||a[0]!=='TR3'||a[2]!==V||!['J','B','O'].includes(a[1]))throw Error('Wrong QR version or type');return a}
function readJoin(text){const a=parse(text);if(a[1]!=='J'||a.length!==10||!idOK(a[3])||typeof a[4]!=='string'||!/^[A-Z0-9_-]{3,12}$/.test(a[4])||!['A','B'].includes(a[9]))throw Error('Not a valid team JOIN QR');const rules={lives:String(a[5]),seconds:a[6],medic:a[7],wait:a[8]};if(!validRules(rules))throw Error('Invalid host rules');if(s)throw Error('This phone already has a game. Export before reset.');if(h&&h.gid!==a[3])throw Error('This host phone belongs to another game; export/reset host setup first.');pending={gid:a[3],game:a[4],rules,team:a[9]};view='preview';render();notice(`Assigned Team ${pending.team}. Enter your callsign.`)}
function createHost(){if(s||h){notice('Existing player or host game: export and reset before creating another.');return}const game=$('game').value.trim().toUpperCase(),rules={lives:$('lives').value,seconds:Number($('bleed').value),medic:$('medic').value,wait:$('medic').value==='two'?30:0};if(!/^[A-Z0-9_-]{3,12}$/.test(game)||!validRules(rules)){notice('Use a 3–12 character game name, 1–20 or Unlimited lives, and 30–600 whole seconds.');return}const host={version:V,gid:ident(),game,rules,created:now()};if(saveHost(host)){view='host';notice('Game created. Show JOIN A only to Team A, then JOIN B to Team B. Post BASE codes at their bases.')}}
function join(){if(!pending||s)return;const name=$('name').value.trim();if(!name||name.length>32){notice('Enter a callsign (up to 32 characters).');return}const p=pending, count=p.rules.lives==='U'?1:Number(p.rules.lives);const next={version:V,gid:p.gid,game:p.game,rules:p.rules,team:p.team,name,id:ident(),tags:Array.from({length:count},()=>({status:'LIVE'})),phase:'ACTIVE',offer:null,wins:[],medics:[],seen:[],medPending:null,events:[]};event(next,`Joined ${p.game}, Team ${p.team}; ${rulesText(p.rules)}`);if(save(next)){pending=null;notice(`Team ${s.team} assigned. Call HIT and mark out before using the phone.`)}}
function available(){return s&&s.tags.some(t=>t.status==='LIVE')}
function eliminated(){return s&&s.phase==='ELIMINATED'}
function offered(){return s&&s.phase==='OFFERED'&&s.offer&&s.tags[s.offer.n-1]?.status==='OFFERED'}
function timedOut(){return offered()&&now()>=s.offer.deadline}
function reconcile(){if(timedOut()){change(x=>{const n=x.offer.n;x.tags[n-1].status='LOST';x.offer=null;x.phase=x.rules.lives!=='U'&&!x.tags.some(t=>t.status==='LIVE')?'ELIMINATED':'RETURN';event(x,`Life ${n} expired and was spent; ${x.phase==='ELIMINATED'?'eliminated':'return to base'}`)});notice(s.phase==='ELIMINATED'?'Final life expired — ELIMINATED.':'Bleedout expired. Life spent; respawn at base.')}}
function hit(){reconcile();if(!s||s.phase!=='ACTIVE'||!available())return;const n=s.tags.findIndex(t=>t.status==='LIVE')+1,at=now();change(x=>{x.tags[n-1].status='OFFERED';x.phase='OFFERED';x.offer={n,id:ident(),at,deadline:at+x.rules.seconds*1000};event(x,`Life ${n} offered until ${stamp(at+x.rules.seconds*1000)}`)})}
function lose(){reconcile();if(!offered())return;const n=s.offer.n;if(!confirm(`Spend life ${n}? Have the enemy watch the bar change to red.`))return;reconcile();if(!offered())return;change(x=>{x.tags[n-1].status='LOST';x.offer=null;x.phase=x.rules.lives!=='U'&&!x.tags.some(t=>t.status==='LIVE')?'ELIMINATED':'RETURN';event(x,`Life ${n} lost by witnessed tap; ${x.phase==='ELIMINATED'?'eliminated':'return to base'}`)});notice(s.phase==='ELIMINATED'?'All lives spent — eliminated.':'Life spent. Return to your team base.')}
function heal(){reconcile();if(!offered()||s.rules.medic==='none')return;const n=s.offer.n,word=s.rules.medic==='one'?'one teammate scan':'two teammate scans 30 seconds apart';if(!confirm(`Did a Team ${s.team} teammate show a completed ${word} before the timer expired? Restore life ${n}?`))return;reconcile();if(!offered())return;change(x=>{x.tags[n-1].status='LIVE';x.offer=null;x.phase='ACTIVE';event(x,`Life ${n} medic restored by witnessed tap`)});notice('Medic complete — saved life is green. No base scan needed.')}
function validateOffer(a){if(a.length!==16||!idOK(a[3])||!idOK(a[9])||!idOK(a[12])||!['A','B'].includes(a[8])||typeof a[10]!=='string'||!a[10].trim()||a[10].length>32||!Number.isInteger(a[11])||!Number.isSafeInteger(a[13])||!Number.isSafeInteger(a[14])||!Number.isSafeInteger(a[15]))throw Error('Malformed offer QR');const r={lives:String(a[4]),seconds:a[5],medic:a[6],wait:a[7]};if(!validRules(r)||a[14]!==a[13]+r.seconds*1000||a[11]<1||a[11]>(r.lives==='U'?1:Number(r.lives)))throw Error('Invalid offer data');if(a[3]!==s.gid||JSON.stringify(r)!==JSON.stringify(s.rules))throw Error('Different game ID or locked rules');if(a[9]===s.id)throw Error('Cannot scan your own offer');if(now()>=a[14])throw Error('Offer expired. No capture or medic after bleedout');if(a[13]>now()+60000)throw Error('Phone clocks differ; check time settings');return {team:a[8],owner:a[9],name:a[10],n:a[11],offer:a[12],issued:a[13],deadline:a[14],challenge:a[15]}}
function accept(text){reconcile();if(!s)throw Error('Join a team first');const a=parse(text);if(a[1]==='B'){if(a.length!==5||!idOK(a[3])||a[3]!==s.gid||a[4]!==s.team)throw Error('Wrong game or team base QR');if(s.phase!=='RETURN')throw Error('Base scan only works while returning to base');change(x=>{if(x.rules.lives==='U')x.tags[0].status='LIVE';x.phase='ACTIVE';event(x,`Team ${x.team} base QR scanned; respawned (finite red lives stay spent)`)});notice('Respawn complete. Available lives only.');return}
if(a[1]!=='O')throw Error('This QR is not a playable offer');if(s.phase!=='ACTIVE')throw Error('Cannot capture or medic while out, offered or eliminated');const o=validateOffer(a);if(o.team===s.team){if(s.rules.medic==='none')throw Error('Medics disabled for this game');if(s.medics.some(m=>m.offer===o.offer))throw Error('Already medic assisted this offer');const m=s.medPending;if(s.rules.medic==='one'){change(x=>{x.medics.push({...o,at:now()});x.medPending=null;event(x,`One-scan medic assisted ${o.name} life ${o.n}; owner must confirm`)});notice(`💉 Show ${o.name} success; they tap MEDIC COMPLETE before expiry.`);return}
if(!m||now()>=m.deadline){change(x=>{x.medPending={...o,started:now()};event(x,`Two-scan medic started for ${o.name} life ${o.n}`)});notice('First scan saved. Stay together; scan a FRESH QR after at least 30 seconds, before bleedout ends.');return}
if(m.owner!==o.owner||m.offer!==o.offer)throw Error('Finish or cancel your current medic attempt first');if(o.challenge===m.challenge)throw Error('Need a fresh rotating QR from the same offer');if(now()-m.started<s.rules.wait*1000)throw Error(`Wait ${Math.ceil((s.rules.wait*1000-(now()-m.started))/1000)} more seconds`);change(x=>{x.medics.push({...o,at:now()});x.medPending=null;event(x,`Two-scan medic assisted ${o.name} life ${o.n}; owner must confirm`)});notice(`💉 Show ${o.name} success; they tap MEDIC COMPLETE before expiry.`);return}
if(s.seen.includes(o.offer))throw Error('This offer was already captured on your phone');change(x=>{x.seen.push(o.offer);x.wins.push({...o,at:now()});event(x,`Captured ${o.name} life ${o.n} (honour-system scan; watch owner tap LIFE LOST)`)});notice(`🏆 Captured ${o.name}. Watch them tap LIFE LOST and turn red.`)}
function cancelMedic(){if(!s?.medPending)return;change(x=>{event(x,'Abandoned two-scan medic attempt cancelled');x.medPending=null});notice('Medic attempt cancelled.')}
function timer(){const el=$('timer');if(!el||!offered())return;const seconds=Math.max(0,Math.ceil((s.offer.deadline-now())/1000));el.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} remaining`}
function refreshOffer(){if(!offered())return;const ch=Math.floor(now()/8000);if(ch===lastChallenge)return;lastChallenge=ch;const el=$('offerqr');if(el){const code=offerCode();shownOffer=code;qr(el,code,215)}}
function renderSetup(){const active=!!s;$('setup').classList.toggle('hidden',active);$('play').classList.toggle('hidden',!active);if(active)return;const which=h&&view==='choose'?'host':view;for(const id of ['choose','hostForm','hostPanel','joinPanel','joinPreview'])$(id).classList.add('hidden');const name={choose:'choose',form:'hostForm',host:'hostPanel',join:'joinPanel',preview:'joinPreview'}[which]||'choose';$(name).classList.remove('hidden');$('oldExport').classList.toggle('hidden',!localStorage.getItem(OLD));if(which==='host'&&h){$('hostInfo').textContent=`${h.game} · ID ${h.gid.slice(0,8)} · ${rulesText(h.rules)}`;showHostCode('J','A','hostCode')}if(which==='preview'&&pending){$('previewTeam').textContent=`TEAM ${pending.team} — ${pending.game}`;$('previewRules').textContent=rulesText(pending.rules)}}
function showHostCode(type,team,target){if(!h)return;const box=$(target),code=type==='J'?joinCode(team):baseCode(team),key=`${target}:${code}`;if(shownHost===key&&box.childNodes.length)return;shownHost=key;box.replaceChildren();const title=document.createElement('h2');title.textContent=`TEAM ${team} ${type==='J'?'JOIN':'BASE'} QR`;box.append(title);const square=document.createElement('div');square.className='qr';box.append(square);qr(square,code,215);const hint=document.createElement('p');hint.className='compact';hint.textContent=type==='J'?'Show only to assigned players before play.':'Post this code physically at Team '+team+' base. It does NOT assign a team.';box.append(hint)}
function renderPlay(){if(!s)return;const phase=s.phase,returning=phase==='RETURN',dead=phase==='ELIMINATED';document.body.classList.toggle('returning',returning);document.body.classList.toggle('mist',dead);$('identity').textContent=`${s.name} · Team ${s.team} · ${s.game} · ${rulesText(s.rules)} · ID ${s.gid.slice(0,8)}`;const bar=$('bar');bar.replaceChildren();s.tags.forEach((t,i)=>{const el=document.createElement('span');el.className='segment '+t.status;el.title=`Life ${i+1}: ${t.status}`;bar.append(el)});bar.setAttribute('aria-label',`Life status: ${s.tags.map(t=>t.status).join(', ')}`);$('actions').className='actions'+(returning?' single':dead||phase==='OFFERED'?' off':'');$('hit').disabled=phase!=='ACTIVE'||!available();$('scan').disabled=!['ACTIVE','RETURN'].includes(phase);const st=$('stage');st.replaceChildren();lastChallenge=-1;shownOffer='';if(phase==='OFFERED'&&offered()){const title=document.createElement('h2');title.textContent=`LIFE ${s.offer.n} OFFERED`;st.append(title);const time=document.createElement('p');time.id='timer';time.className='timer';st.append(time);const q=document.createElement('div');q.id='offerqr';q.className='qr';st.append(q);const msg=document.createElement('p');msg.className='offer-info';msg.textContent='Enemy scans once; you tap LIFE LOST while they watch.'+(s.rules.medic==='none'?'':` Team medic: ${s.rules.medic==='one'?'one scan':'two scans 30s apart'}; show success.`);st.append(msg);if(s.rules.medic!=='none'){const m=document.createElement('button');m.className='alt';m.textContent='MEDIC COMPLETE';m.onclick=heal;st.append(m)}const lost=document.createElement('button');lost.className='danger';lost.textContent=`LIFE LOST — ${s.team}${s.offer.n}`;lost.onclick=lose;st.append(lost);timer();refreshOffer()}else{const title=document.createElement('h2');title.textContent=returning?'RESPAWN AT BASE':dead?'ELIMINATED':'Call HIT and mark out before using your phone.';st.append(title);if(returning){const p=document.createElement('p');p.textContent='Scan your assigned team base QR. Spent finite lives stay red.';st.append(p)}if(dead){const p=document.createElement('p');p.textContent='Leave play safely. Help, history and export remain below.';st.append(p)}}
const groups=new Map();for(const w of s.wins){const g=groups.get(w.owner)||{name:w.name,events:[]};g.events.push(w);groups.set(w.owner,g)}const wall=$('trophies');wall.replaceChildren();if(!groups.size)wall.textContent='None yet';for(const g of groups.values()){const b=document.createElement('button');b.className='tile';const bold=document.createElement('strong');bold.textContent=`🏆${g.events.length}`;const short=document.createElement('span');short.textContent=g.name.slice(0,4).toUpperCase();b.append(bold,short);b.onclick=()=>{const area=$('dialogtext');area.replaceChildren();const head=document.createElement('h2');head.textContent=g.name;area.append(head);for(const w of [...g.events].reverse()){const p=document.createElement('p');p.textContent=`${w.team}${w.n} · ${w.offer.slice(0,10)} · ${stamp(w.at)}`;area.append(p)}$('dialog').showModal()};wall.append(b)}$('medals').textContent=s.medics.length?`💉 ${s.medics.length} medic assists`:'';$('history').replaceChildren();for(const e of [...s.events].reverse()){const item=document.createElement('li');item.textContent=`${e.at}: ${e.message}`;$('history').append(item)}$('pendingBox').classList.toggle('hidden',!s.medPending);$('pendingInfo').textContent=s.medPending?`Waiting for second scan of ${s.medPending.name}; expires ${stamp(s.medPending.deadline)}.`:'';$('hostTools').classList.toggle('hidden',!h||h.gid!==s.gid)}
function render(){renderSetup();renderPlay()}
async function stopScan(){const item=scanner;scanner=null;scanBusy=false;if(item){try{await item.stop()}catch(e){}try{item.clear()}catch(e){}}$('camera').classList.add('hidden');$('joincamera').classList.add('hidden')}
async function startScan(kind){reconcile();if(kind==='play'&&!s)return;await stopScan();if(typeof Html5Qrcode!=='function'){notice('Scanner library unavailable. Connect once online, reload, then test offline.');return}const joinMode=kind==='join',container=$(joinMode?'joincamera':'camera'),reader=joinMode?'joinreader':'reader';container.classList.remove('hidden');try{const item=new Html5Qrcode(reader);scanner=item;await item.start({facingMode:'environment'},{fps:8,qrbox:{width:190,height:190}},async text=>{if(scanBusy)return;scanBusy=true;await stopScan();try{joinMode?readJoin(text):accept(text)}catch(e){notice(e.message)}},()=>{})}catch(e){notice('Camera could not start: '+e.message);await stopScan()}}
function download(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function exportLog(){if(s)download(s,`tag-relay-v3-${s.game}-${s.team}-${s.id.slice(0,6)}.json`)}
function resetPlayer(){if(!s||!confirm('Export first. Erase this phone\'s v3 player lives, trophies and history? Host setup (if any) remains.'))return;localStorage.removeItem(KEY);s=null;view=h?'host':'choose';document.body.classList.remove('returning','mist');render();notice('v3 player reset. v2 and v1 data remain untouched.')}
$('hostStart').onclick=()=>{view='form';render()};$('backHost').onclick=()=>{view='choose';render()};$('createHost').onclick=createHost;$('joinStart').onclick=()=>{view='join';render()};$('joinBack').onclick=()=>{view=h?'host':'choose';render()};$('joinScan').onclick=()=>startScan('join');$('joinStop').onclick=stopScan;$('joinRead').onclick=()=>{try{readJoin($('joinManual').value)}catch(e){notice(e.message)}};$('previewBack').onclick=()=>{pending=null;view=h?'host':'join';render()};$('joinConfirm').onclick=join;$('hostPlay').onclick=()=>{view='join';render();notice('The host can choose a team on this phone using the host code buttons, or scan a JOIN code on another display.')} ;
for(const [id,type,team,target] of [['joinA','J','A','hostCode'],['joinB','J','B','hostCode'],['baseA','B','A','hostCode'],['baseB','B','B','hostCode'],['playJoinA','J','A','playHostCode'],['playJoinB','J','B','playHostCode'],['playBaseA','B','A','playHostCode'],['playBaseB','B','B','playHostCode']])$(id).onclick=()=>{showHostCode(type,team,target);if(type==='J'&&target==='hostCode'&&view==='join'){readJoin(joinCode(team))}};
$('hostReset').onclick=()=>{if(s){notice('Export and reset the player game first.');return}if(confirm('Erase host setup and all four QR codes on THIS phone? Export/print codes first.')){localStorage.removeItem(HOST);h=null;view='choose';shownHost='';render();notice('Host setup erased. Existing player phones are NOT changed.')}};
$('hit').onclick=hit;$('scan').onclick=()=>startScan('play');$('stop').onclick=stopScan;$('readmanual').onclick=async()=>{await stopScan();try{accept($('manual').value);$('manual').value=''}catch(e){notice(e.message)}};$('cancelMedic').onclick=cancelMedic;$('export').onclick=exportLog;$('reset').onclick=resetPlayer;$('closeDialog').onclick=()=>$('dialog').close();$('oldExport').onclick=()=>{try{const old=JSON.parse(localStorage.getItem(OLD));download(old,'tag-relay-v2-backup.json')}catch(e){notice('Saved v2 log could not be read. Do not erase browser data.')}};
for(let i=1;i<=20;i++){const option=document.createElement('option');option.value=String(i);option.textContent=String(i);if(i===5)option.selected=true;$('lives').append(option)}
try{const raw=localStorage.getItem(HOST);if(raw){const x=JSON.parse(raw);if(x.version!==V||!idOK(x.gid)||!validRules(x.rules))throw Error('host');h=x;view='host'}}catch(e){notice('Saved host data unreadable. Do not reset before backup.')}try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);if(x.version!==V||!idOK(x.gid)||!idOK(x.id)||!validRules(x.rules)||!Array.isArray(x.tags)||x.tags.length!==(x.rules.lives==='U'?1:Number(x.rules.lives))||!['ACTIVE','OFFERED','RETURN','ELIMINATED'].includes(x.phase)||!Array.isArray(x.events)||!Array.isArray(x.wins)||!Array.isArray(x.medics)||!Array.isArray(x.seen))throw Error('player');s=x}}catch(e){notice('Saved v3 state unreadable. Do not reset or clear storage.')}render();reconcile();setInterval(()=>{reconcile();timer();refreshOffer();if(s?.medPending&&now()>=s.medPending.deadline){change(x=>{x.medPending=null;event(x,'Medic attempt expired')})}},1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){reconcile();timer();refreshOffer()}});
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>notice('Offline cache setup failed. Reload while online before airplane-mode testing.'));
})();